apiVersion: v1
kind: Service
metadata:
 name: server-service
 namespace: ${NAMESPACE}
 labels:
   app: flask
spec:
 type: NodePort
 ports:
 - port: 3000
   name: http
   nodePort: 30080
 selector:
   app: flask
