apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: database-service
spec:
  type: NodePort
  ports:
  - name: mysql
    port: 3306
    nodePort: 32000
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
