apiVersion: serving.knative.dev/v1
kind: Deployment
metadata:
 name: knative-server
spec:
 selector:
  matchLabels:
   app: flask
 replicas: 1 
 template:
   metadata:
     labels:
       app: flask
   spec:
     containers:
     - name: knative_server
       image: ${IMAGE}
       ports:
       - containerPort: 3000
     imagePullSecrets:
     - name: ${SECRET}
